### ISSUE TITLE
Table number is not stored under order details

### ISSUE THREAD

**Issue by ealvarezdetoledo** [thoughtco/ti-ext-tables#1]
Hi,

The extension works perfectly. I can successfully point a user to s paeecific table using the proper route.

I then also, added a small tweak to notify the user it's table has been detected (line23 of routes.php file):

`flash()->success(sprintf(lang('thoughtco.tables::default.welcome_message')) . $id);`

I then go on to place the order normally, but when I access the order in the back-end, it does not seem to be storing the table number in each order.

![image](https://user-images.githubusercontent.com/56493928/106382899-d5ff0f80-63c2-11eb-81cc-5e33fa013fd2.png)

**Comment by ryanmitchell** [comment]
This is not meant to be a useable extension - more a starting point for you to work from. You need to amend the order manager in cart to actually fill the table value.

**Comment by ealvarezdetoledo** [comment]
Thanks Ryan!

In case it helps anyone, I made this changes, and now works perfectly! You need to make a series of modifications to extensions/cart/classes/OrderManager.php. I detailed them below:

Add this to line 15 of the file.

`use Session;`

Then, add this attribute to the function GetCustomerAttributes (line 269):

`'table_number' => "",`

Lastly, write the table stored in session 

```
$tableData = Session::get('thoughtco.tables');
	$order->table_number = $tableData['table'];
```

Best,

**Comment by ryanmitchell** [comment]
Feel free to open a PR to add this to the read me?

**Comment by ealvarezdetoledo** [comment]
Done ;)
